= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2019/20
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Justin Bürger

**Gruppe:** 36

== Was habe ich gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
Ich habe vorrangig den Umgang mit Spring, html und Thymeleaf gelernt. Davon hatte ich überhaupt keine Ahnung und mittlerweile fühle ich mich nicht mehr komplett ahnungslos.

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Mein Team war großartig. Und ich habe, wieder einmal, gelernt, wie wichtig Kommunikation ist. Wir haben uns beinahe jede Woche getroffen (außerhalb des Meetings) und über Probleme, Herangehensweisen, etc. gesprochen. Das hat den ganzen Prozess nicht nur sehr viel "sauberer" gemacht, sondern auch angenehmer.
Beim nächsten Mal würde ich mir selber vorher nicht so viele andere Verpflichtungen (Lehrveranstaltungen, zwei Nebenjobs, etc) aufladen. Ich hatte kein gutes Gefühl dabei, nur meinen "Pflichtteil" zu erledigen, während die anderen mit vollem Elan dabei waren und ihre Aufgaben über das geforderte Maß hinweg erledigten. Dadurch erlangten sie natürlich auch eine Expertise und waren stets hilfsbereit bei Problemen, bei denen mir dann die Erfahrung fehlte, um sie zu lösen. Ich bin meinem Team sehr dankbar dafür. Für das nächste Teamprojekt, werde ich mir das zu Herzen nehmen und hoffe dann genauso begeisterte Kollegen zu haben.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
SalesPoint ist, soweit ich das beurteilen kann, schön aufgebaut, konsistent und logisch. Die Dokumentation war auch gut, allerdings hätte ich mir etwas mehr "Fleisch" gewünscht. Man kam zwar schnell rein, aber bei technischen Details, war nicht viel aus der Doku herauszuholen. Vielleicht lässt sich ja da eine Lösung finden. Es wurden ja eine Menge Fragen im Auditorium beantwortet, vielleicht lassen sich diese ja sammeln und zur Verfügung stellen? Dann müsste Oliver die gleichen Fragen nicht allen beantworten, sondern man könnte auf diese Sammlung verweisen.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Ehrlich gesagt, abseits von der Geschichte mit Salespoint, fällt mir da nicht viel ein. Das Auditorium ist super, der Lernraum soll auch sehr gut sein - wer Hilfe braucht, bekommt sie definitiv.
Andererseits wäre eine kleine Einführung zur Front-End-Entwicklung cool. Davon hatte ich keine Ahnung und ein wenig Vorwissen, hätte den Prozess da einfacher gemacht. Wie relevant das ist, hängt natürlich davon ab, wie viele Informatik-Stundenten vorher html nicht angefasst haben.


== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Ich habe mich durch Marvin und Julian kompetent betreut gefühlt. Beide haben gut kommuniziert, was die Aufgabe ist und waren informiert über den "offiziellen" Ablauf des Praktikums. Auch schön war, dass sie zwar den Kunden gut "gespielt" haben, aber dennoch mit dem Hintergrund, dass wir alle noch lernen und Fehler passieren können. Das war sehr angenehm. Antworten auf Fragen waren immer fix da und die Meetings waren zwar alle produktiv, trotzdem hat es nicht an Humor gefehlt. Ich war vollkommen zufrieden.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
